import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { confirm, input } from "@inquirer/prompts";
import kleur from "kleur";

type EnvMap = Record<string, string>;

async function promptOptional(message: string, help?: string): Promise<string> {
  return (
    await input({
      message: help ? `${message} ${kleur.dim(help)}` : message,
      default: "",
    })
  ).trim();
}

async function promptRequired(message: string, validate?: (v: string) => string | true): Promise<string> {
  const value = await input({
    message,
    validate: (v) => {
      const trimmed = v.trim();
      if (!trimmed) return "value required";
      return validate ? validate(trimmed) : true;
    },
  });
  return value.trim();
}

function validateStripeTestKey(v: string): string | true {
  if (v.startsWith("sk_test_") || v.startsWith("rk_test_")) return true;
  return "Stripe key must start with sk_test_ or rk_test_ — live keys are refused for safety";
}

function renderEnvFile(env: EnvMap): string {
  const header = `# Generated by rc-retention-brain init on ${new Date().toISOString()}\n`;
  const lines: string[] = [header];

  const sections: { title: string; keys: string[] }[] = [
    { title: "# LLM", keys: ["ANTHROPIC_API_KEY"] },
    {
      title: "# RevenueCat",
      keys: ["REVENUECAT_API_KEY", "REVENUECAT_PROJECT_ID"],
    },
    { title: "# Stripe", keys: ["STRIPE_API_KEY"] },
    {
      title: "# Sentry",
      keys: ["SENTRY_AUTH_TOKEN", "SENTRY_ORG_SLUG", "SENTRY_PROJECT_SLUG", "SENTRY_DSN"],
    },
    {
      title: "# PostHog",
      keys: [
        "POSTHOG_PERSONAL_API_KEY",
        "POSTHOG_PROJECT_ID",
        "POSTHOG_PROJECT_API_KEY",
        "POSTHOG_HOST",
      ],
    },
  ];

  for (const section of sections) {
    lines.push(section.title);
    for (const key of section.keys) {
      lines.push(`${key}=${env[key] ?? ""}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export async function runInit(): Promise<void> {
  const envPath = resolve(process.cwd(), ".env");

  console.log(kleur.cyan().bold("rc-retention-brain init"));
  console.log(kleur.dim("Configures .env for sources and the LLM. Press enter to skip optional fields."));
  console.log("");

  if (existsSync(envPath)) {
    const overwrite = await confirm({
      message: `.env already exists at ${envPath} — overwrite?`,
      default: false,
    });
    if (!overwrite) {
      console.log(kleur.yellow("aborted — .env left untouched"));
      return;
    }
  }

  const env: EnvMap = {};

  console.log(kleur.cyan("LLM"));
  env.ANTHROPIC_API_KEY = await promptOptional(
    "Anthropic API key (sk-ant-...)",
    "— required for LLM intervention generation, optional otherwise"
  );

  console.log("");
  console.log(kleur.cyan("Subscription source (≥1 required)"));

  // RevenueCat
  const rcKey = await promptOptional("RevenueCat API key (sk_...)", "— leave blank to skip");
  if (rcKey) {
    env.REVENUECAT_API_KEY = rcKey;
    env.REVENUECAT_PROJECT_ID = await promptRequired("RevenueCat project ID (proj_...)");
  }

  // Stripe — keep prompting until valid or empty
  let stripeKey = "";
  for (;;) {
    const value = await promptOptional(
      "Stripe test mode key (sk_test_...)",
      "— leave blank to skip"
    );
    if (!value) break;
    const valid = validateStripeTestKey(value);
    if (valid === true) {
      stripeKey = value;
      break;
    }
    console.log(kleur.red(`  ${valid}`));
  }
  if (stripeKey) env.STRIPE_API_KEY = stripeKey;

  if (!rcKey && !stripeKey) {
    console.log("");
    console.log(
      kleur.red(
        "✗ at least one subscription source is required (RevenueCat or Stripe). Re-running prompts."
      )
    );

    // Re-prompt until at least one is provided.
    for (;;) {
      const rcRetry = await promptOptional(
        "RevenueCat API key (sk_...)",
        "— leave blank to skip"
      );
      if (rcRetry) {
        env.REVENUECAT_API_KEY = rcRetry;
        env.REVENUECAT_PROJECT_ID = await promptRequired("RevenueCat project ID (proj_...)");
        break;
      }
      let stripeRetry = "";
      for (;;) {
        const value = await promptOptional(
          "Stripe test mode key (sk_test_...)",
          "— leave blank to skip"
        );
        if (!value) break;
        const valid = validateStripeTestKey(value);
        if (valid === true) {
          stripeRetry = value;
          break;
        }
        console.log(kleur.red(`  ${valid}`));
      }
      if (stripeRetry) {
        env.STRIPE_API_KEY = stripeRetry;
        break;
      }
      console.log(kleur.red("  still no source — please enter one to continue"));
    }
  }

  console.log("");
  console.log(kleur.cyan("Optional sources"));

  // Sentry
  const sentryToken = await promptOptional(
    "Sentry auth token",
    "— leave blank to skip"
  );
  if (sentryToken) {
    env.SENTRY_AUTH_TOKEN = sentryToken;
    env.SENTRY_ORG_SLUG = await promptRequired("Sentry org slug");
    env.SENTRY_PROJECT_SLUG = await promptRequired("Sentry project slug");
    const dsn = await promptOptional(
      "Sentry DSN",
      "— optional, only needed for seed-sandbox writes"
    );
    if (dsn) env.SENTRY_DSN = dsn;
  }

  // PostHog
  const phKey = await promptOptional(
    "PostHog personal API key (phx_...)",
    "— leave blank to skip"
  );
  if (phKey) {
    env.POSTHOG_PERSONAL_API_KEY = phKey;
    env.POSTHOG_PROJECT_ID = await promptRequired("PostHog project ID");
    const projectApiKey = await promptOptional(
      "PostHog project API key (phc_...)",
      "— optional, only needed for seed-sandbox writes"
    );
    if (projectApiKey) env.POSTHOG_PROJECT_API_KEY = projectApiKey;
    const host = await promptOptional("PostHog host", "— defaults to https://us.posthog.com");
    env.POSTHOG_HOST = host || "https://us.posthog.com";
  }

  await writeFile(envPath, renderEnvFile(env), "utf8");

  console.log("");
  console.log(kleur.green().bold(`✅ wrote ${envPath}`));

  const configured: string[] = [];
  if (env.REVENUECAT_API_KEY) configured.push("RevenueCat");
  if (env.STRIPE_API_KEY) configured.push("Stripe");
  if (env.SENTRY_AUTH_TOKEN) configured.push("Sentry");
  if (env.POSTHOG_PERSONAL_API_KEY) configured.push("PostHog");
  console.log(kleur.dim(`   sources: ${configured.join(", ")}`));
  if (env.ANTHROPIC_API_KEY) {
    console.log(kleur.dim("   LLM: enabled (intervention drafts will be generated)"));
  } else {
    console.log(kleur.dim("   LLM: disabled (set ANTHROPIC_API_KEY later to enable drafts)"));
  }

  console.log("");
  console.log(kleur.cyan("Next steps:"));
  console.log("  npx rc-retention-brain seed-sandbox --train-days 30 --eval-days 30");
  console.log("  npx rc-retention-brain run");
  console.log(kleur.dim("  npx rc-retention-brain reveal-future   # validate predictions later"));
}
