import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { confirm, input, select } from "@inquirer/prompts";
import kleur from "kleur";

const EXAMPLE_MCP_JSON = JSON.stringify(
  {
    sources: [
      {
        label: "subscriptions",
        command: "<your MCP launch command, e.g. npx>",
        args: ["<args>", "<for the MCP server>"],
        tool: "<tool name to call for backfill>",
        mapper: "llm",
        hint: "subscription billing events (purchases, renewals, cancellations)",
      },
    ],
  },
  null,
  2
);

export async function runInit(): Promise<void> {
  console.log(kleur.bold("retention-brain init (MCP-only build)"));
  console.log(
    kleur.dim(
      "This build pulls events exclusively via Model Context Protocol servers. " +
        "All data sources — RevenueCat, Stripe, PostHog, Sentry, anything — are wired through their MCP."
    )
  );
  console.log();

  // 1. .env for the LLM provider
  const envPath = resolve(process.cwd(), ".env");
  const envOverwrite =
    !existsSync(envPath) ||
    (await confirm({ message: ".env already exists — overwrite?", default: false }));

  if (envOverwrite) {
    const provider = await select({
      message: "Which LLM provider will draft interventions?",
      choices: [
        { name: "Anthropic (claude-sonnet-4-6 / claude-opus-4-7 critic)", value: "anthropic" },
        { name: "OpenAI (gpt-5 creative / gpt-4o structured + critic)", value: "openai" },
        { name: "Skip — set later", value: "skip" },
      ],
    });

    const lines: string[] = [`# Generated by retention-brain init on ${new Date().toISOString()}`, ""];
    if (provider !== "skip") {
      lines.push(`LLM_PROVIDER=${provider}`);
      const keyName = provider === "openai" ? "OPENAI_API_KEY" : "ANTHROPIC_API_KEY";
      const value = (
        await input({
          message: `${keyName} ${kleur.dim("(paste here, or leave blank and edit .env later)")}`,
          default: "",
        })
      ).trim();
      lines.push(`${keyName}=${value}`);
    }
    lines.push("");
    await writeFile(envPath, lines.join("\n"), "utf8");
    console.log(kleur.green(`✓ wrote ${envPath}`));
  }

  // 2. .retention-brain/mcp.json template
  const mcpDir = resolve(process.cwd(), ".retention-brain");
  const mcpPath = resolve(mcpDir, "mcp.json");
  const writeTemplate =
    !existsSync(mcpPath) ||
    (await confirm({
      message: ".retention-brain/mcp.json already exists — overwrite with template?",
      default: false,
    }));

  if (writeTemplate) {
    if (!existsSync(mcpDir)) await mkdir(mcpDir, { recursive: true });
    await writeFile(mcpPath, EXAMPLE_MCP_JSON + "\n", "utf8");
    console.log(kleur.green(`✓ wrote template to ${mcpPath}`));
  }

  console.log();
  console.log(kleur.bold("Next steps:"));
  console.log(`  1. Edit ${kleur.cyan(".retention-brain/mcp.json")} to point at your MCP servers (Stripe, PostHog, Sentry, RevenueCat — whatever).`);
  console.log(`     Each entry needs: ${kleur.dim("label, command (or url), tool, mapper")}.`);
  console.log(`  2. ${kleur.cyan("pnpm retb run")} to pull events, score risk, and write today's briefing.`);
  console.log();
  console.log(kleur.dim("Schema and field reference: README.md → \"Plug any MCP\""));
}
