import { generateObject } from "ai";
import { z } from "zod";
import { getModel, type UserTimeline, type Event } from "@retention-brain/core";
import type { RiskScore } from "@retention-brain/risk-engine";
import { sanitizeUserIdForFilename } from "./filename-safety.js";

const Schema = z.object({
  title: z.string().max(120),
  summary: z.string().max(500),
  proposed_action: z.string().max(800),
  fix_direction: z.string().max(500).optional(),
  severity: z.enum(["low", "medium", "high"]),
});

export type EngineeringPlayCopy = z.infer<typeof Schema>;

export type EngineeringTicket = {
  user_id: string;
  filename: string;
  markdown: string;
  copy: EngineeringPlayCopy;
};

const CRASH_KINDS = new Set(["error.crash", "error.client"]);

/**
 * True when the user's signal profile warrants an engineering ticket alongside
 * (or instead of) a user-directed intervention. Triggers on either a strong
 * heuristic error_rate signal or 2+ crashes in the last 14 days.
 */
export function needsEngineeringPlay(
  risk: RiskScore,
  timeline: UserTimeline,
  nowIso?: string
): boolean {
  const hasCrashSignal = risk.top_signals.some(
    (s) => s.name === "error_rate" && s.score > 0
  );
  if (hasCrashSignal) return true;

  const now = nowIso ? new Date(nowIso).getTime() : Date.now();
  // Inclusive "last 14 days" window. The boundary case matters: a crash at
  // exactly midnight 14 days ago should count, not get silently excluded by
  // a strict-greater-than.
  const cutoff = now - 14 * 86_400_000;
  const recentCrashes = timeline.events.filter(
    (e) =>
      CRASH_KINDS.has(e.kind) &&
      new Date(e.timestamp).getTime() >= cutoff
  );
  return recentCrashes.length >= 2;
}

export async function generateEngineeringTicket(
  risk: RiskScore,
  timeline: UserTimeline,
  opts: { date: Date }
): Promise<EngineeringTicket | null> {
  if (!needsEngineeringPlay(risk, timeline, opts.date.toISOString())) {
    return null;
  }

  const crashes = timeline.events.filter((e) => CRASH_KINDS.has(e.kind));
  const crashLines = crashes
    .map((e) => `- ${e.timestamp.slice(0, 16)} · ${e.kind}${formatPayloadDetail(e)}`)
    .join("\n");

  const { object } = await generateObject({
    model: getModel("structured"),
    schema: Schema,
    system:
      "You write engineering stabilization tickets for indie or small-team subscription app devs. " +
      "There is no separate engineering team — the person reading this is the same person who fixes the bug. " +
      "Be concrete and short. The ticket should be skimmable in 60 seconds: what is broken, why it matters for retention, what to investigate first.",
    prompt:
      `User: ${risk.user_id}\n` +
      `Risk score: ${risk.score.toFixed(2)}\n` +
      `Narrative: ${risk.narrative}\n` +
      `Crash events:\n${crashLines || "(no crash events in window)"}\n\n` +
      `Write a stabilization ticket with:\n` +
      `- title: short, descriptive (≤120 chars). Mention the affected user and the symptom.\n` +
      `- summary: 2–3 sentences explaining what's happening and why it matters for retention (≤500 chars).\n` +
      `- proposed_action: concrete next step — what to investigate, where to look, how to verify the fix (≤800 chars).\n` +
      `- fix_direction (optional): if the event pattern suggests a likely root cause, name it (≤500 chars). Leave empty if unclear.\n` +
      `- severity: low / medium / high based on crash count, recency, and whether the user has churned.`,
  });

  const slug = object.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  const dateStr = opts.date.toISOString().slice(0, 10);
  const safeUserId = sanitizeUserIdForFilename(risk.user_id);
  const filename = `${dateStr}-${safeUserId}-${slug || "stabilization"}.md`;

  const markdown = renderTicketMarkdown(risk, timeline, object, opts.date, crashes);

  return {
    user_id: risk.user_id,
    filename,
    markdown,
    copy: object,
  };
}

function renderTicketMarkdown(
  risk: RiskScore,
  timeline: UserTimeline,
  copy: EngineeringPlayCopy,
  date: Date,
  crashes: Event[]
): string {
  const lines: string[] = [];
  lines.push(`# ${copy.title}`);
  lines.push("");
  lines.push(`Generated by retention-brain on ${date.toISOString().slice(0, 10)}`);
  lines.push(`Severity: ${copy.severity}`);
  lines.push(`Affected user: \`${risk.user_id}\`${timeline.email ? ` (${timeline.email})` : ""}`);
  lines.push(`Risk score: ${risk.score.toFixed(2)}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(copy.summary);
  lines.push("");
  lines.push("## Why this matters");
  lines.push("");
  lines.push(`> ${risk.narrative}`);
  lines.push("");
  if (crashes.length > 0) {
    lines.push("## Crash evidence");
    lines.push("");
    for (const e of crashes) {
      lines.push(`- ${e.timestamp.slice(0, 16)} · ${e.kind}${formatPayloadDetail(e)}`);
    }
    lines.push("");
  }
  lines.push("## Proposed action");
  lines.push("");
  lines.push(copy.proposed_action);
  lines.push("");
  if (copy.fix_direction && copy.fix_direction.trim().length > 0) {
    lines.push("## Likely fix direction");
    lines.push("");
    lines.push(`> ${copy.fix_direction}`);
    lines.push("");
    lines.push("_LLM-inferred from the event pattern — verify before shipping._");
    lines.push("");
  }
  lines.push("## Next steps");
  lines.push("");
  lines.push("- [ ] Reproduce the crash locally");
  lines.push("- [ ] Confirm root cause matches the LLM's guess (or correct it)");
  lines.push("- [ ] Ship the fix");
  lines.push("- [ ] Verify on the next briefing run that this user (and similar users) stop showing the signal");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    "_This ticket was auto-generated from a user's event timeline. The proposed action and fix direction are starting points, not verified plans. Always confirm root cause before shipping._"
  );
  return lines.join("\n");
}

function formatPayloadDetail(e: Event): string {
  const p = e.payload as Record<string, unknown>;
  const parts: string[] = [];
  for (const key of ["reason", "feature", "amount", "currency", "type", "sentiment", "code", "message"]) {
    const v = p[key];
    if (v !== undefined && v !== null && v !== "") parts.push(`${key}=${String(v)}`);
  }
  return parts.length > 0 ? ` · ${parts.join(" ")}` : "";
}
